#!/bin/bash
set -Eeuo pipefail

curr_dir="$(realpath .)"
music_dir="$curr_dir"
search_dir="$curr_dir"
# when PLAY_MUSIC_DIR is set in the environment ...
if  [ -v PLAY_MUSIC_DIR ] ; then
    music_dir="$PLAY_MUSIC_DIR"
    # ... and the current directory is not inside MUSIC_DIR
    if [[ ! "$curr_dir" = "$(realpath $music_dir)"* ]]; then
        # regex search relative to music dir
        search_dir="$music_dir"
    fi
fi

telnet=false
if [ -v PLAY_VLC_TELNET_PORT ]; then
    telnet=true
    telnet_port="$PLAY_VLC_TELNET_PORT"
    if [ -v PLAY_VLC_TELNET_PW ]; then
        telnet_pw="$PLAY_VLC_TELNET_PW"
    else
        telnet_pw=""
    fi
fi
telnet_host=127.0.0.1 #hardcoded for now
# parse cli args
help_shown=false
list_only=false
append=false
read_paths_from_file=""
sorted=false
patterns_found=false
args=( "$@" )
while [ ${#args[@]} -gt 0 ]; do
    arg="${args[0]}"
    if [[ "$arg" == -[!-][a-zA-z]* ]]; then
        targ=${arg[@]:2}
        arg="${arg[@]:0:2}"
        targs=( "$arg" )
        while [ "$targ" != "" ]; do
            targs=( "${targs[@]}" "-${targ[@]:0:1}" )
            targ="${targ[@]:1}"
        done
        args=( "${targs[@]}" "${args[@]:1}")
    fi
    if [ "$arg" = "-h" ] || [ "$arg" = "--help" ]; then
        help_shown=true
        #display help
        cat <<________EOF
play [-f FILE] [-hansc] [PATTERNS...]
    Play all PATTERNS in VLC Media Player. 
    Patterns matching a filename play that file.
    Patterns matching a directory recursively play all songs in that directory.
    Patterns starting with ~ are treated as a regex of paths to exclude.
    Any other patterns are interpreted as a regex for a file search.

    When the environment sets MUSIC_DIR, that directory is used for 
    regex searches and also checked for file / directory maches.

    Calling play with no PATTERNS / FILE is equivalent to play *.

    -h | --help    : show this help
    -a | --append  : instead of playing the songs, append them to the playlist
    -n | --dry-run : don't play, just print out the results to stdout
    -s | --sort    : play in sorted order (default is random) 
    -f | --file    : read additional PATTERNS from FILE
    -c | --clear   : clear the playlist beforehand 
________EOF
        shift
    elif [ "$arg" = "-a" ] || [ "$arg" = "--append" ]; then
        append=true
    elif [ "$arg" = "-n" ] || [ "$arg" = "--dry-run" ]; then
        list_only=true
    elif [ "$arg" = "-s" ] || [ "$arg" = "--sort" ]; then
        sorted=true
    elif [ "$arg" = "-f" ] || [ "$arg" = "--file" ]; then
        args=( "${args[@]:1}" )
        if [[ "${args[@]}" == "" ]]; then
            echo "missing parameter for $arg"
            exit -1
        fi
        f="${args[0]}"
        if [ "$f" == "-" ]; then
            f="/dev/stdin"
        elif [ ! -f "$f" ]; then
            echo "cannot access file '$f'" 1>&2
            exit -1
        fi
        while read line; do
            args=( "${args[@]}" "$line" )
        done < $f
    elif [ "$arg" = "-c" ] || [ "$arg" = "--clear" ]; then
        #without the sleep sometimes vlc doesn't start back up :/
        #TODO: proper fix for this
        (killall vlc 2>/dev/null && sleep 0.1) || : 
    elif [ "$arg" = "--" ]; then
        break
    elif [[ "$arg" == -* ]]; then
        echo "unknown option '$arg'"
        exit -1
    else
        patterns_found=true
        break
    fi
    args=( "${args[@]:1}" )
done
if [ $patterns_found == false ]; then 
    if [ $help_shown == false ]; then
        echo "invalid arguments. try --help" >&2
        exit 1
    fi
    exit 0
fi
music_regex='^.*\.\(mp3\)\|\(opus\)\|(m4a)\|(ogg)$'
if $list_only; then
    shell_cmd="grep '$music_regex' | xargs -d\\\\n -I@ realpath --relative-to='.' @"
else
    if $telnet; then
        #make sure vlc is running
        vlc --one-instance -I qt --extraintf telnet --telnet-host $telnet_host --telnet-port $telnet_port --telnet-password $telnet_pw 2>/dev/null &
        #wait for the telnet interface to come alive
        while ! nc -q 0 $telnet_host $telnet_port  </dev/null >/dev/null; do sleep 0.01; done      

        nc_cmd="nc -q 0 $telnet_host $telnet_port >/dev/null"
        if $append; then
            shell_cmd="(echo '$telnet_pw' && sed \"s/.*/enqueue &/\" && printf 'quit\n\n') | $nc_cmd" 
        else
            shell_cmd="(echo '$telnet_pw' && (read first && echo \"add \$first\" && sed \"s/.*/enqueue &/\") && printf 'quit\n\n') | $nc_cmd" 
        fi
    else
        if $append; then
            shell_cmd="xargs -d \\\\n vlc --playlist-enque 2>/dev/null &"
        else
            shell_cmd="(read first && xargs -d \\\\n vlc \"\$first\" --playlist-enque 2>/dev/null &)"
        fi
    fi

fi

if $sorted; then
    ordering_cmd="sort -uV"
else
    ordering_cmd="sort -u | shuf"
fi

has_exclusions=false
excluded="" 
patterns=()
for arg in "${args[@]}"; do
   if [[ "$arg" =~ ~.* ]]; then
       if [ "$excluded" = "" ]; then
           excluded="(${arg:1})"
       else
           excluded="$excluded|(${arg:1})"
       fi
   else
        patterns=( "${patterns[@]}" "$arg")
   fi 
done

if [ "$excluded" != "" ]; then
    shell_cmd="pcregrep -v '$excluded' | $shell_cmd"
fi

if [ ${#patterns[@]} -eq 0 ]; then
    #play everything in folder
    find "$search_dir" -type f | bash -c "$ordering_cmd | grep '$music_regex' | $shell_cmd"
else 
    #play every file, everything in folder and everything matching pattern
    cat <(
        for arg in "${patterns[@]}"; do
            if [ -f "$curr_dir/$arg" ]; then
                echo "$curr_dir/$arg"
            elif [ -d "$curr_dir/$arg" ]; then
                find "$curr_dir/$arg" -type f
            elif [ -f "$music_dir/$arg" ]; then
                echo "$music_dir/$arg"
            elif [ -d "$music_dir/$arg" ]; then
                find "$music_dir/$arg" -type f
            else
                find "$search_dir" -type f | pcregrep -i -- "$arg"
            fi
        done
    ) | bash -c "$ordering_cmd | grep '$music_regex' | $shell_cmd"
fi
